apiVersion: v1
kind: Pod
metadata:
  name: nfs-test-pod
  namespace: devops
spec:
  containers:
  - name: test-container
    image: busybox
    command: ["/bin/sh", "-c", "while true; do echo $(date) >> /mnt/data/output.txt; sleep 1; done"]
    volumeMounts:
    - name: nfs-volume
      mountPath: /mnt/data
  volumes:
  - name: nfs-volume
    persistentVolumeClaim:
      claimName: pvc-nfs-static-data 
