apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-nfs-static-data 
  namespace: devops
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi