apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nfs-static-data
  namespace: devops
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: "/srv/nfs_share/exports/static"
    server: 192.168.1.63
#  hostPath:
#    path: "/mnt/data"